### ISSUE TITLE
Generating timesheets is broken

### ISSUE THREAD

**Issue by vogt31337** [navariltd/nl-attendance-timesheet#11]
Hi,

I am trying your module with the newest version of frappe hrms and I get the following error:

### App Versions
```
{
	"erpnext": "15.43.3",
	"frappe": "15.48.0",
	"hrms": "16.0.0-dev",
	"nl_attendance_timesheet": "0.0.1"
}
```
### Route
```
Form/Timesheet Center/Timesheet Center
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1725, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/nl_attendance_timesheet/nl_attendance_timesheet/controllers/generate_overtime_timesheets.py", line 49, in generate_overtime_timesheets
    attendance_records = query.run(as_dict=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 229, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabShift Type.unpaid_breaks_minutes' in 'SELECT'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"start_date": "2024-11-01",
		"end_date": "2024-11-30"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/nl_attendance_timesheet.controllers.generate_overtime_timesheets.generate_overtime_timesheets",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabShift Type.unpaid_breaks_minutes' in 'SELECT'\")",
	"exc_type": "OperationalError",
	"_exc_source": "nl_attendance_timesheet (app)"
}
```

**Comment by maniamartial** [comment]
Will create version-16 soon and get back.

**Comment by maniamartial** [comment]
Hello @vogt31337 , you can delete the nl_attendance_timesheet patches from Patch Log and run migration again 
Or you can just run migration, and check on custom field, field like _unpaid_breaks_minutes_ should be created.

Let me know incase of any issue, if not, I will close this in weeks time.

**Comment by vogt31337** [comment]
Thanks for the fast reply, i am currently trying Version 15. But let me Test IT a bit more. I Had to redo the Install several Times...
